language: c

os:
  - linux
  - osx
env:
  - LIBAV=libav-stable
  - LIBAV=libav-git
  - LIBAV=ffmpeg-stable
  - LIBAV=ffmpeg-git
compiler:
  - clang

branches:
  only:
    - master
    - ci

matrix:
  exclude:
    - os: osx
      env: LIBAV=libav-stable
    - os: osx
      env: LIBAV=libav-git
    - os: osx
      env: LIBAV=ffmpeg-git

before_install: ./travis-deps libass-stable $LIBAV
script:
  - ./bootstrap.py
  - ./waf configure
  - ./waf build

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#mpv-player-dev"
    on_success: change
    on_failure: always
