blank_issues_enabled: false
contact_links:
  - name: mpv irc channel
    url: https://mpv.io/community/
    about: Feel free to ask question here irc://irc.freenode.net/mpv
  - name: mpv irc developer channel
    url: https://mpv.io/community/
    about: Ask question related to the development of mpv here
           irc://irc.freenode.net/mpv-devel
